// Generated by CoffeeScript 1.10.0
(function() {
  var main;

  main = function() {
    $('.menu-icon').click(function() {
      $('.menu').animate({
        left: '0px'
      });
      return $('body').animate({
        left: '200px'
      });
    });
    return $('.close-icon').click(function() {
      $('.menu').animate({
        left: '-200px'
      });
      return $('body').animate({
        left: "0px"
      });
    });
  };

  $(document).ready(main);

}).call(this);
